### ISSUE TITLE
!nostalgia can be used on channels which a user doesn't have access to

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/EfficientEnigma#16]
By using the ID of a channel, any user can view a channel hidden from them with !nostalgia. Not a problem unless the ID gets out, but still something that should be checked for.

**Comment by alex85120** [comment]
Perhaps we could add this code into nostalgia.py:
```python
if searchin.permissions_for(message.author).read_messages == False:
    await client.send_message(message.channel, "You don't have permission to see messages from that channel!")```

**Comment by Tymewalk** [comment]
#19 fixed this.
