### ISSUE TITLE
!help should not generate the way it does

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/EfficientEnigma#17]
It should actually check settings flags and output it specially, rather than just lumping everything in at random.

**Comment by AlexTheJPEG** [comment]
Perhaps we could print specific help for a command when a user types something like `!help nostalgia`, and if they type nothing or an invalid command, the bot will just print the entire help. That's what I did with my bot.

**Comment by Tymewalk** [comment]
@alex85120 That'd work a lot better, the only problem is how commands specify their own help.

Probably not too hard though, if needed it could just be hardcoded or done in `setup_command_table`.

**Comment by AlexTheJPEG** [comment]
Actually, come to think of it, maybe we can just put a brief description of each command for the bot to post. See pull request #21, this will probably suffice.

**Comment by Tymewalk** [comment]
Unfortunately, merging #21 broke the commands - I'll have to undo it and then rewrite how it works.

I can just make a similar table for help, though.

**Comment by Tymewalk** [comment]
Dunno why this never got closed - it's fixed now.
